services:
  app:
    build: .
    ports:
      - "8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgres://root:passwordCity@db:5432/primary"
    command: fastapi dev --host 0.0.0.0
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:17-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwordCity
      POSTGRES_DB: primary
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d primary" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:

networks:
  venn-game:
